#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2006 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# Tests for file ending with a newline

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --explain:       print an explanation with solving instructions, then exit
#   --installed      file is to be installed
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use strict;
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::Utils;

my ($Prog)    = "endswithnewline";
my ($Version) = "1.2";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f) = $ARGV[0];
open(F, "$f") || die "Couldn't open $f";

my (@lines) = <F>;
close(F);

my ($lstr) = "line\# " . ($#lines + 1);
my ($line) = pop @lines;

if (!$line || $line =~ m/\n$/) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  print "=> $line\n"  if (&verboseArg());
  print "$lstr (1)\n" if (!&quietArg());
  Exit 1;
}

sub Help
{
  print "Check that file ends with a newline\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print
"Files that do not end with a newline character can cause problems. Please add a newline character to the end of the file.\n";
  Exit 0 if &explainArg();
}
