#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2007 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# Tests KDE source for Qt Classes to be avoided or replaced with a KDE class

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --check-sets:    list of checksets
#   --explain:       print an explanation with solving instructions
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use warnings;
use strict;
use Cwd 'abs_path';
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::PreProcess;
use Krazy::Utils;

my ($Prog)    = "qclasses";
my ($Version) = "1.42";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f) = $ARGV[0];

my ($filetype) = &fileType($f);
unless (&usingKDECheckSet() && ($filetype eq "c++" || $filetype eq "designer")) {
  print "okay\n" if (!&quietArg());
  Exit 0;
}

# open file and slurp it in
open my $fh, '<:encoding(UTF-8)', $f or die;
my (@data_lines) = <$fh>;
close($fh);

# Remove C-style comments and #if 0 blocks from the file input
my (@lines);
if ($filetype eq "c++") {
  @lines = RemoveIfZeroBlockC(RemoveCommentsC(@data_lines));
} else {
  @lines = @data_lines;
}

my ($cnt)     = 0;
my ($linecnt) = 0;
my ($lstr)    = "";

my ($line);
while ($linecnt < $#lines) {
  $line = $lines[$linecnt++];
  if ($filetype eq "c++") {
    if ( $line =~ m+//.*[Kk]razy:excludeall=.*$Prog+
      || $line =~ m+//.*[Kk]razy:skip+)
    {
      $cnt = 0;
      last;
    }
    next if ($line =~ m+//.*[Kk]razy:exclude=.*$Prog+);
    $line =~ s+//.*++;    #skip C++ comments
  }

  # Don't use these deprecated Qt classes.
  &doIt($line, "QHttp",      "KIO%COLON%%COLON%AccessManager", '');
  &doIt($line, "QWorkspace", "QMdiArea",                       '');

  # These Qt classes should be avoided in KDE
  &doIt($line, "QErrorMessage", "KMessageBox", '');

  # These KDE classes provide additional features over their Qt counterparts
  if (&strictArg() eq "super") {
    &doIt($line, "QComboBox", "KComboBox", '');
  }
  &doIt($line, "QTextEdit", "KTextEdit", '');
}

if (!$cnt) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  print "$lstr" if (!&quietArg());
  Exit $cnt;
}

sub doIt()
{
  my ($line, $qname, $kname, $nregexp) = @_;
  if ($f !~ m/$kname\.c/i && &qClass($line, $qname, $nregexp)) {
    $cnt++;
    $lstr .= "Use $kname instead of $qname line\#" . $linecnt . "\n";
    print "=> $line\n" if (&verboseArg());
  }
}

sub qClass()
{
  my ($l, $qname, $nregexp) = @_;

  if ($filetype eq "c++") {
    if (
         $l =~ m/new\s+$qname\s*\(/
      || $l =~ m/[\s=,]+$qname\::[[:alnum:]]+[[:space:]]*[\w\(\)\;]/
      || $l =~ m/$qname[[:space:]]*\*[[:space:]]*[[:alnum:]]+/
      || $l =~ m/[:,]\s*public\s+$qname/
      || ( ($l =~ m/=[[:space:]]*$qname\::/ || $l =~ m/=[[:space:]]*$qname[[:space:]]*\(/)
        && ($l !~ m/==/ && $l !~ m/\!=/))
      )
    {
      return 0 if ($nregexp ne "" && $l =~ m/$nregexp/);
      return 0 if ($l                   =~ m/(foreach|Q_FOREACH)\s*\(\s*$qname/);
      return 1 if (!&whiteList($l));
    }
  }

  if ($filetype eq "designer") {
    if ($l =~ m/class=\"$qname\"/) {
      return 0 if ($nregexp ne "" && $l =~ m/$nregexp/);
      return 1 if (!&whiteList($l));
    }
  }

  return 0;
}

sub whiteList
{
  my ($l) = @_;
  if ( $l =~ m/QUrl::toPercentEncoding/
    || $l =~ m/QUrl::fromPercentEncoding/
    || $l =~ m/QUrl::toAce/
    || $l =~ m/QUrl::fromAce/
    || $l =~ m/QLineEdit::dropEvent/
    || $l =~ m/QDialog::DialogCode/
    || $l =~ m/QDialog::accept/
    || $l =~ m/QDialog::Accepted/
    || $l =~ m/QDialog::reject/
    || $l =~ m/QDialog::Rejected/
    || $l =~ m/QMessageBox::AcceptRole/
    || $l =~ m/QMessageBox::RejectRole/
    || $l =~ m/QMessageBox::Question/
    || $l =~ m/QMessageBox::Warning/
    || $l =~ m/QTabWidget::North/
    || $l =~ m/QTabWidget::South/
    || $l =~ m/[:,]\s*public\s+QDialog/
    || $l =~ m/class=\"QDialog\"/
    || $l =~ m/KServiceTypeTrader::createInstanceFromQuery<.*>/)
  {
    return 1;
  } else {
    return 0;
  }
}

sub Help
{
  print "Check for Qt classes that should not be used or have KDE improvements\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print
"Use the KDE version of some Qt GUI elements to provide a consistent look and feel for the KDE desktop. The KDE classes add extra functionality to the Qt base class. Also see <https://community.kde.org/Policies/API_to_Avoid>. Please refer to the API documentation for details before porting to the Kfoo classes.\n";
  Exit 0 if &explainArg();
}
