#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
    if 0; # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# Copyright (C) 2006-2008 by Allen Winter <winter@kde.org>                    #
# Copyright (C) 2003 by Dirk Mueller <mueller@kde.org>                        #
# Copyright (C) 2004 Richard Evans <rich@ridas.com>                           #
#                                                                             #
# All the real work in this program uses code derived from kde-spellcheck.pl  #
# written by Dirk Mueller <mueller@kde.org> and later modified by             #
# Richard Evans <rich@ridas.com>.  You may find kde-spellcheck.pl in          #
# the kdesdk module, in the scripts subdirectory.                             #
#                                                                             #
# This program is free software; you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation; either version 2 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program; if not, write to the Free Software                 #
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA. #
#                                                                             #
###############################################################################

# Tests KDE source for spelling errors

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --explain:       print an explanation with solving instructions, then exit
#   --installed      file is to be installed
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use strict;
use Getopt::Long;
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::PreProcess;
use Krazy::Utils;

my($Prog) = "spelling";
my($Version) = "1.5";

my($help) = '';
my($version) = '';
my($explain) = '';
my($installed) = '';
my($quiet) = '';
my($verbose) = '';

exit 1
if (!GetOptions('help' => \$help, 'version' => \$version,
                'explain' => \$explain, 'installed' => \$installed,
                'verbose' => \$verbose, 'quiet' => \$quiet));

&Help() if $help;
&Version() if $version;
&Explain() if $explain;
if ($#ARGV != 0){ &Help(); exit 0; }

my $DICTIONARY = build_dictionary_lookup_table();
exit &check_file($ARGV[0]);

##############################################################################
sub Help {
  print "Check for spelling errors\n";
  exit 0 if $help;
}

sub Version {
  print "$Prog, version $Version\n";
  exit 0 if $version;
}

sub Explain {
  print "Spelling errors in comments and strings should be fixed as they may show up later in API documentation, handbooks, etc.  Misspelled strings make the translator's job harder. Please use US English.\n";
  exit 0 if $explain;
}

sub info{
  print @_ if ($verbose);
}

sub check_file
{
  my $filename = shift;
  my $fh;

  unless ( open $fh, "<", $filename )
  {
    warn "Failed to open: '$filename': $!";
    return;
  }

  my @contents      = <$fh>;

  close $fh or warn "Failed to close: '$filename': $!";

  my $original;
  my $cnt = 0;
  my $linecnt = 0;
  my $line;
  my $lstr = "";
  for ( @contents )
  {
    $linecnt++;
    $original = $_;

    if ($original =~ m+//.*[Kk]razy:excludeall=.*$Prog+ ||
        $original =~ m+//.*[Kk]razy:skip+) {
      $cnt = 0;
      last;
    }
    next if ($original =~ m+http://+ ||
             $original =~ m+https://+ ||
             $original =~ m+ftp://+);  # skip lines with urls

    next if (fileType($filename) eq "desktop" &&
	     ($original =~ m+^Comment\[.*\]+ ||
	      $original =~ m+^Keywords\[.*\]+ ||
	      $original =~ m+^X-KDE-Keywords\[.*\]+ ||
	      $original =~ m+^Name\[.*\]+ ||
	      $original =~ m+^GenericName\[.*\]+));

    next if (fileType($filename) eq "c++" &&
	     ($original =~ m/^\s*#\s*include/));;

    next if ($original =~ m+//.*[Kk]razy:exclude=.*$Prog+);

    $_=~s/&//g;
    for my $word ( split /[^\w']/ )    # \W would split on apostrophe
    {
      $word=lc($word) if ($word =~ /^[A-Z]/);
      next unless defined (my $correction = $DICTIONARY->{$word});

      s/\b$word\b/$correction/g;

      $cnt++;
      if ($cnt == 1) {
        $lstr = "line\#" . $linecnt . "[$word]";
      } else {
        $lstr = $lstr . "," . $linecnt . "[$word]";
      }
      info "$filename ($linecnt): $word => $correction\n";
    }
  }

  if (!$cnt) {
    print "okay\n" if (!$quiet);
    return 0;
  } else {
    print "$lstr ($cnt)\n" if (!$quiet);
    return $cnt;
  }
}

sub build_dictionary_lookup_table
{
  my %hash;

  while (<DATA>) {
    next if /^\s*$/ or /^\s*#/;   # Skip blank lines and comments

    next unless /^\s*"([^"]+)"\s+(.*)\s*$/ or /^\s*(\S+)\s+(.*)\s*$/;

    if ( $1 eq $2 ) {
      warn "WARNING: Ignoring identical misspelling and correction: '$1' in __DATA__ offset line $.\n";
      next;
    }

    $hash{$1} = $2;
  }

  return \%hash;
}

# permit the following words
#acknowledgement        acknowledgment
#acknowledgements       acknowledgments
#acknowlege             acknowledge
#behaviour              behavior
#cancelation            cancellation
#cancelled              canceled
#cancelling             canceling
#colour                 color
#colours                colors
#dialogue               dialog
#favourable             favorable
#favour                 favor
#favourite              favorite
#favours                favors
#honour                 honor
#honouring              honoring
#initialisation         initialization
#initialise             initialize
#initialising           initializing
#minimise               minimize
#minimising             minimizing
#neighbourhood          neighborhood
#neighbour              neighbor
#neighbour              neighbor
#neighbours             neighbors
#organisational         organizational
#organisation           organization
#organisation           organization
#organisations          organizations
#organised              organized
#organise               organize
#organiser              organizer
#organising             organizing
#organising             organizing
#recognised             recognized
#recognise              recognize
#recognises             recognizes
#centre                 center
#centre                 center
#chatwindow             chat window
#contactlist            contact list

__DATA__

#incorrect spelling    correction

aasumes                assumes
abailable              available
abbrevation            abbreviation
abbrevations           abbreviations
abbriviate             abbreviate
abbriviation           abbreviation
abilties               abilities
ablolute               absolute
abreviate              abbreviate
acces                  access
accesible              accessible
accesing               accessing
accomodate             accommodate
accross                across
acess                  access
achive                 achieve
achived                achieved
achiving               achieving
acknoledged            acknowledged
acommodate             accommodate
aconyms                acronyms
acording               according
acount                 account
acouting               accounting
activ                  active
actons                 actions
acually                actually
adapater               adapter
adatper                adapter
addded                 added
adddress               address
additinoally           additionally
additionaly            additionally
additionaly            additionally
additionnal            additional
additonal              additional

#incorrect spelling    correction

addtional              additional
aditional              additional
adminstrator           administrator
adminstrator           administrator
adress                 address
adress                 address
adressed               addressed
adresses               addresses
advertize              advertise
aesthetic              esthetic
afganistan             afghanistan
agressive              aggressive
agressive              aggressive
agressively            aggressively
alignement             alignment
alligned               aligned
allignment             alignment
allmost                almost
allready               already
allways                always
allways                always
alook                  a look
alot                   a lot
alows                  allows
alrady                 already
alreay                 already
alternativly           alternatively
ammount                amount
ammount                amount
analagous              analogous
analizer               analyzer
analogue               analog
analyse                analyze
analyses               analyzes
anfer                  after
angainst               against
annoucement            announcement
announcments           announcements
anwer                  answer
anwser                 answer
anwsers                answers
aplication             application
appeareance            appearance
appearence             appearance
appeares               appears
apperarance            appearance
appers                 appears

#incorrect spelling    correction

applicaiton            application
applicalble            applicable
appliction             application
appplication           application
approciated            appreciated
appropiate             appropriate
approriate             appropriate
approximatly           approximately
apropriate             appropriate
aquire                 acquire
aquired                acquired
arbitarily             arbitrarily
arbitary               arbitrary
arbitary               arbitrary
aribrary               arbitrary
aribtrarily            arbitrarily
aribtrary              arbitrary
arround                around
assosciated            associated
assosiated             associated
assoziated             associated
asssembler             assembler
assumend               assumed
asume                  assume
asynchonous            asynchronous
asyncronous            asynchronous
atempt                 attempt
aticles                articles
atleast                at least
atomicly               atomically
attatchment            attachment
auhor                  author
authentification       authentication
authoratative          authoritative
authorisations         authorizations
automaticaly           automatically
automaticaly           automatically
automaticly            automatically
autoreplacment         autoreplacement
auxilary               auxiliary
auxilary               auxiliary
avaible                available
avaible                available
availble               available
availibility           availability
availible              available
availible              available
avaliable              available
avaluate               evaluate
avare                  aware
aviable                available
backrefences           backreferences
baloon                 balloon
basicly                basically

#incorrect spelling    correction

basicly                basically
beautifull             beautiful
becuase                because
beeep                  beep
beeing                 being
beexported             be exported
befor                  before
beggining              beginning
begining               beginning
belarussian            belarusian
beteen                 between
betrween               between
betweeen               between
blueish                bluish
bofore                 before
bosth                  both
botton                 bottom
boudaries              boundaries
boundries              boundaries
boundry                boundary
boxs                   boxes
bruning                burning
buton                  button
buxfixes               bugfixes
cacheing               caching
calulation             calculation
capabilites            capabilities
caracters              characters
cataloge               catalog
cataloge               catalog
catalogue              catalog
catched                caught
ceneration             generation
centralised            centralized
changable              changeable
chaning                changing
characers              characters
charachters            characters
characteres            characters
charakters             characters
charater               character
chatacter              character
childs                 children
choosed                chose
choosen                chosen
choosen                chosen

#incorrect spelling    correction

chosing                choosing
cirumstances           circumstances
classess               classes
cloumn                 column
coffie                 coffee
colaboration           collaboration
collecion              collection
collumns               columns
coloum                 column
coloumn                column
colum                  column
comamnd                command
comination             combination
commense               commence
commerical             commercial
comming                coming
commited               committed
commiting              committing
commiting              committing
commmand               command
commuication           communication
communcation           communication
compability            compatibility
comparision            comparison
comparision            comparison
comparisions           comparisons
compatability          compatibility
compatibilty           compatibility
compatiblity           compatibility
compedium              compendium
compiiled              compiled
compleion              completion
completly              completely
complient              compliant
comsumer               consumer
comunication           communication
concatonated           concatenated
concurent              concurrent
configration           configuration
configuraton           configuration
connent                connect
connnection            connection
consecutivly           consecutively
consequtive            consecutive
constuctors            constructors
containg               containing
contexual              contextual
contigious             contiguous
contingous             contiguous
continouos             continuous

#incorrect spelling    correction

continous              continuous
continous              continuous
contiribute            contribute
contoller              controller
contorll               control
controler              controller
controling             controlling
controll               control
conver                 convert
convient               convenient
convinience            convenience
conviniently           conveniently
coordiator             coordinator
copys                  copies
coresponding           corresponding
corrent                correct
correponds             corresponds
costraints             constraints
coudn't                couldn't
coursor                cursor
coverted               converted
coypright              copyright
cricles                circles
criticisim             criticism
cryptograhy            cryptography
culculating            calculating
curren                 current
currenty               currently
curteousy              courtesy
custimize              customize
customisation          customization
customise              customize
customise              customize
customised             customized
cutsom                 custom
cutt                   cut
cutt                   cut
datas                  data
dcopcient              dcopclient
deactive               deactivate
deamon                 daemon
debuging               debugging
debuging               debugging
decriptor              descriptor
defaul                 default
defered                deferred
defininition           definition
defintions             definitions
deleteing              deleting
demonsrative           demonstrative
denstiy                density
depencies              dependencies

#incorrect spelling    correction

dependeds              depends
dependend              dependent
dependig               depending
depricated             deprecated
derfined               defined
derivs                 derives
descide                decide
desciptor              descriptor
descryption            description
desctroyed             destroyed
desiabled              disabled
desidered              desired
desination             destination
deskop                 desktop
dekstop                desktop
desription             description
desription             description
destiantion            destination
determiend             determined
determins              determines
detremines             determines
develloped             developed
developerss            developers
developped             developed
devided                divided
devide                 divide
diabled                disabled
diable                 disable
diaglostic             diagnostic
dialag                 dialog
dialler                dialer
dialler                dialer
dialling               dialing
dialling               dialing
diaog                  dialog
didnt                  didn't
diffcult               difficult
differenciate          differentiate
differenly             differently
differntiates          differentiates
dificulty              difficulty
difusion               diffusion
digitised              digitized
diplayed               displayed
dirctely               directly
dirctory               directory
direcory               directory
directorys             directories
directoy               directory
disactivate            deactivate
disappers              disappears
disbale                disable

#incorrect spelling    correction

discontigous           discontiguous
discpline              discipline
discription            description
disppear               disappear
dissassembler          disassembler
distingush             distinguish
distribtuion           distribution
distrubutor            distributor
divizor                divisor
docucument             document
documentaiton          documentation
documentors            documenters
doens't                doesn't
doesnt                 doesn't
donnot                 do not
dont                   don't
dont't                 don't
dou                    do
draging                dragging
dreamt                 dreamed
droped                 dropped
duotes                 quotes
durring                during
dynamicly              dynamically
eallocate              deallocate
eample                 example
editory                editor
efficent               efficient
efficently             efficiently
effiency               efficiency
elemt                  element
embedabble             embeddable
embedable              embeddable
embeddabble            embeddable
embeded                embedded
emcompass              encompass
emited                 emitted
emty                   empty
encyption              encryption
enhandcements          enhancements
enles                  endless
enought                enough
entitities             entities
entrys                 entries
entrys                 entries
enumarated             enumerated
envirnment             environment
envirnoment            environment
enviroment             environment
environemnt            environment
environent             environment
equador                ecuador
equiped                equipped
equlas                 equals

#incorrect spelling    correction

errorous               erroneous
errror                 error
escriptor              descriptor
espacially             especially
espesially             especially
evalute                evaluate
everytime              every time
exacly                 exactly
exapmle                example
excecpt                except
execeeded              exceeded
execess                excess
exection               execution
execuable              executable
executeble             executable
exept                  except
exisiting              existing
existance              existence
exlusively             exclusively
exmaple                example
experienceing          experiencing
explicitely            explicitly
explicity              explicitly
explit                 explicit
expresion              expression
expresions             expressions
extented               extended
extention              extension
extention              extension
extentions             extensions
extesion               extension
fabilous               fabulous
falg                   flag
familar                familiar
fastes                 fastest
featue                 feature
feeded                 fed
filsystem              filesystem
firware                firmware
fisrt                  first
fixiated               fixated
fixiate                fixate
fixiating              fixating
flaged                 flagged
flavours               flavors
focussed               focused
folllowed              followed
follwing               following
folowing               following

#incorrect spelling    correction

folowing               following
footnotexs             footnotes
formaly                formally
fortunatly             fortunately
foward                 forward
fragement              fragment
framesyle              framestyle
framset                frameset
fucntion               function
fucntion               function
fuction                function
fuctions               functions
fufill                 fulfill
fulfiling              fulfilling
fullfilled             fulfilled
funcion                function
funciton               function
functin                function
funtional              functional
funtionality           functionality
funtion                function
funtions               functions
furthur                further
gaalxies               galaxies
gamee                  game
gernerated             generated
ges                    goes
ghostscipt             ghostscript
giude                  guide
globaly                globally
goind                  going
gostscript             ghostscript
grapphis               graphics
greyed                 grayed
guaranted              guaranteed
guarenteed             guaranteed
guarrantee             guarantee
gziped                 gzipped
handeling              handling
harware                hardware
harware                hardware
hasnt                  hasn't
havn't                 haven't
heigt                  height
heigth                 height
hiddden                hidden
hierachical            hierarchical
highlighlighted        highlighted
highligting            highlighting
higlighting            highlighting

#incorrect spelling    correction

honours                honors
horziontal             horizontal
hypens                 hyphens
hysical                physical
iconized               iconified
illumnating            illuminating
imaginery              imaginary
imitatation            imitation
immedialely            immediately
immediatly             immediately
imortant               important
imperical              empirical
implemantation         implementation
implemenation          implementation
implenetation          implementation
implimention           implementation
implmentation          implementation
inactiv                inactive
incldue                include
incomming              incoming
incomming              incoming
incovenient            inconvenient
indeces                indices
indentical             identical
indentification        identification
indepedancy            independency
independant            independent
independend            independent
indetectable           undetectable
indicdate              indicate
indice                 index
indictes               indicates
infinitv               infinitive
infomation             information
informaion             information
informatation          information
informationon          information
informations           information
inifity                infinity
inital                 initial
initalization          initialization
initalized             initialized
initalize              initialize
initalize              initialize
initialyze             initialize
initilialyze           initialize
initilization          initialization
initilize              initialize

#incorrect spelling    correction

initilize              initialize
innacurate             inaccurate
innacurately           inaccurately
insde                  inside
inteface               interface
interactivelly         interactively
interfer               interfere
interfrace             interface
interisting            interesting
internationalisation   internationalization
interrrupt             interrupt
interrumped            interrupted
interrups              interrupts
interupt               interrupt
intervall              interval
intervalls             intervals
intiailize             initialize
intial                 initial
intialisation          initialization
intialization          initialization
intialize              initialize
intialize              initialize
intializing            initializing
introdutionary         introductory
introdution            introduction
intrrupt               interrupt
intruction             instruction
invarient              invariant
invokation             invocation
ionisation             ionization
irrevesible            irreversible
isntance               instance
is'nt                  isn't
issueing               issuing
istory                 history
iterface               interface
itselfs                itself
journalised            journalized
judgement              judgment
kdelbase               kdebase
keyboad                keyboard
klicking               clicking
knowlege               knowledge
konquerer              konqueror
konstants              constants
kscreensave            kscreensaver
labelling              labeling
labelling              labeling
lauching               launching
layed                  laid
learnt                 learned
leats                  least
lenght                 length

#incorrect spelling    correction

lenght                 length
licenced               licensed
licence                license
licence                license
licens                 license
liset                  list
listenening            listening
listveiw               listview
litle                  little
litteral               literal
localisation           localization
looged                 logged
losely                 loosely
maanged                managed
maching                matching
magnication            magnification
magnifcation           magnification
mailboxs               mailboxes
maillinglists          mailinglists
maintainance           maintenance
maintainence           maintenance
malicous               malicious
mamage                 manage
managment              management
managment              management
manangement            management
mannually              manually
mantainer              maintainer
manupulation           manipulation
marbels                marbles
matchs                 matches
maximimum              maximum
maxium                 maximum
mdification            modification
mdified                modified
menues                 menus
mesages                messages
messanger              messenger
messanging             messaging
messenging             messaging
microsft               microsoft
millimetres            millimeters
mimimum                minimum
minimun                minimum
minium                 minimum
minumum                minimum
miscelaneous           miscellaneous
miscelanous            miscellaneous
miscellaneaous         miscellaneous
miscellanous           miscellaneous
miscellanous           miscellaneous
mispeled               misspelled
mispelled              misspelled

#incorrect spelling    correction

mistery                mystery
modifes                modifies
modifing               modifying
modul                  module
mosue                  mouse
mozzila                mozilla
mssing                 missing
mulitimedia            multimedia
mulitple               multiple
multible               multiple
multipe                multiple
multy                  multi
mutiple                multiple
neccesary              necessary
neccessary             necessary
necessery              necessary
nedd                   need
neet                   need
negativ                negative
negociated             negotiated
negociation            negotiation
neogtiation            negotiation
nessecarry             necessary
nessecary              necessary
nessesary              necessary
nework                 network
newtork                network
nickanme               nickname
nonexistant            nonexistent
noone                  nobody
noone                  no-one
normalisation          normalization
noticable              noticeable
nucleous               nucleus
obtail                 obtain
occoured               occurred
occouring              occurring
occurance              occurrence
occurances             occurrences
occured                occurred
occurence              occurrence
occurences             occurrences
occure                 occur
occuring               occurring
occurrance             occurrence
occurrances            occurrences
ocupied                occupied
offical                official
ommited                omitted

#incorrect spelling    correction

onthe                  on the
opend                  opened
optimisation           optimization
optionnal              optional
orangeish              orangish
orginate               originate
originaly              originally
orignal                original
oscilating             oscillating
otehr                  other
ouput                  output
outputing              outputting
overidden              overridden
overriden              overridden
overriden              overridden
ownes                  owns
pakage                 package
panelised              panelized
paramaters             parameters
parametres             parameters
parametrize            parameterize
paramter               parameter
paramters              parameters
particip               participle
particularily          particularly
paticular              particular
pendings               pending
percetages             percentages
perfomance             performance
performace             performance
periferial             peripheral
permision              permission
permisions             permissions
permissable            permissible
personalizsation       personalization
perticularly           particularly
phyiscal               physical
plaforms               platforms
plese                  please
politness              politeness
posibilities           possibilities
posibility             possibility

#incorrect spelling    correction

posible                possible
positon                position
possebilities          possibilities
possebility            possibility
possibilty             possibility
possiblity             possibility
posssibility           possibility
potentally             potentially
practise               practice
practising             practicing
preceeded              preceded
preceeding             preceding
precison               precision
preemphasised          preemphasized
preemphasised          preemphasized
prefered               preferred
prefered               preferred
preferrable            preferable
prefiously             previously
preformance            performance
prerequisits           prerequisites
presense               presence
pressentation          presentation
prgramm                program
prining                printing
priveleges             privileges
priviledge             privilege
priviledges            privileges
priviliges             privileges
probatility            probability
probelm                problem
proberly               properly
problmes               problems
proceedure             procedure
proctection            protection
proecss                process
progess                progress
programing             programming
programme              program
programm               program
promille               per mill
promiscous             promiscuous
promped                prompted
pronounciation         pronunciation
pronounciation         pronunciation
pronunce               pronounce
pronunciated           pronounced
properies              properties
propertites            properties
propogate              propagate
protoypes              prototypes

#incorrect spelling    correction

proxys                 proxies
psuedo                 pseudo
psuedo                 pseudo
pult                   desk
purposees              purposes
quatna                 quanta
queing                 queuing
querys                 queries
quiten                 quiet
quiting                quitting
readony                readonly
realise                realize
realy                  really
reamde                 readme
reasonnable            reasonable
receieve               receive
recepeient             recipient
recepient              recipient
recevie                receive
recevie                receive
receving               receiving
recieved               received
recieve                receive
recieve                receive
reciever               receiver
recieves               receives
recieves               receives
recives                receives
recomended             recommended
recommanded            recommended
recommand              recommend
recommented            recommended
redialling             redialing
reets                  resets
refered                referred
refering               referring
refeshes               refreshes
refreshs               refreshes
regarless              regardless
registaration          registration
registred              registered
regsiter               register
regulare               regular
regularily             regularly
reigster               register
reimplemenations       reimplementations

#incorrect spelling    correction

reimplemenations       reimplementations
releated               related
relection              reselection
relevent               relevant
relocateable           relocatable
remaing                remaining
remeber                remember
remebers               remembers
remotley               remotely
renderes               renders
renewd                 renewed
reorienting            reorientating
repalcement            replacement
replys                 replies
reponsibility          responsibility
requeusts              requests
requeriment            requirement
requeriments           requirements
resently               recently
resetted               reset
resistent              resistant
resognized             recognized
resonable              reasonable
resoure                resource
responsability         responsibility
responsivness          responsiveness
resposible             responsible
ressources             resources
retreived              retrieved
retreive               retrieve
retults                results
rewritebles            rewritables
richt                  right
rigths                 rights
rigt                   right
saftey                 safety
satified               satisfied
savely                 safely
savety                 safety
scalled                scaled
scather                scatter
scenerio               scenario
sceptical              skeptical
schduler               scheduler
sectionning            sectioning
selction               selection
selectde               selected
sensistve              sensitive
separed                separated
separeted              separated
sepcified              specified
seperated              separated
seperately             separately
seperate               separate
seperate               separate

#incorrect spelling    correction

seperate               separate
seperation             separation
seperatly              separately
seperator              separator
sequencially           sequentially
sertificate            certificate
serveral               several
setted                 set
sheduled               scheduled
sheme                  scheme
shorctuts              shortcuts
shoud                  should
shouldnt               shouldn't
shouldnt               shouldn't
shure                  sure
similarily             similarly
similiarly             similarly
similiar               similar
simlar                 similar
simpliest              simplest
simultaneuosly         simultaneously
skript                 script
slewin                 slewing
smaple                 sample
sombody                somebody
somehwat               somewhat
soure                  source
sparcely               sparsely
speakiing              speaking
specefied              specified
specfic                specific
specfied               specified
specialised            specialized
specifc                specific
specifed               specified
specificiation         specification
specifieing            specifying
specifing              specifying
specifiy               specify
specifiy               specify
speficied              specified
speling                spelling
spezifying             specifying
sprectrum              spectrum
standar                standard
startp                 startup
statfeul               stateful
statfull               stateful
storeys                storys
straighforward         straightforward
streched               stretched
streches               stretches
strech                 stretch

#incorrect spelling    correction

striked                stroked
stuctures              structures
styleshets             stylesheets
subcribed              subscribed
subdirectorys          subdirectories
subseqently            subsequently
substracting           subtracting
subystem               subsystem
succeded               succeeded
succesfully            successfully
succesful              successful
succesive              successive
succesor               successor
successfull            successful
sucessfull             successful
sucessfully            successfully
sucessfuly             successfully
sucess                 success
sufficent              sufficient
superflous             superfluous
supossed               supposed
supressed              suppressed
supress                suppress
suprised               surprised
susbstitute            substitute
swaped                 swapped
synchonization         synchronization
synchronisation        synchronization
synchronisation        synchronization
synchronised           synchronized
synchronises           synchronizes
synchronise            synchronize
synchronyze            synchronize
syncronization         synchronization
syncronized            synchronized
syncronizes            synchronizes
syncronize             synchronize
syncronizing           synchronizing
syncronizing           synchronizing
syncronous             synchronous
syncrounous            synchronous
syndrom                syndrome
syntex                 syntax
synthetizer            synthesizer
syntheziser            synthesizer
sytem                  system
talbs                  tables
talse                  false
tecnology              technology
temparary              temporary
tempertures            temperatures
terminatin             terminating

#incorrect spelling    correction

texured                textured
themc                  them
thet                   that
threshholds            thresholds
threshhold             threshold
throtte                throttle
throught               through
throuth                through
tiggered               triggered
tihs                   this
timditiy               timidity
timdity                timidity
timming                timing
tranceiver             transceiver
tranfers               transfers
tranfer                transfer
tranlate               translate
tranlation             translation
transalted             translated
transation             transaction
transfering            transferring
transferrable          transferable
transmiter             transmitter
transmiting            transmitting
transmition            transmission
transmittion           transmission
transparancy           transparency
transparant            transparent
trasfered              transferred
traveller              traveler
travelling             traveling
triggerg               triggering
triggerred             triggered
truely                 truly
trys                   tries
uglyness               ugliness
unabiguous             unambiguous
unaccesible            unaccessible
unallowed              disallowed
unamed                 unnamed
unathorized            unauthorized
uncrypted              unencrypted
uncutt                 uncut
underlieing            underlying
underrrun              underrun
undesireable           undesirable
undestood              understood
undexpected            unexpected
undoedne               undid
unecessary             unnecessary
unexperienced          inexperienced
unexperience           inexperience
unfortunatly           unfortunately

#incorrect spelling    correction

unfortunatly           unfortunately
uniq                   unique
unitialized            uninitialized
unkown                 unknown
unmoveable             unmovable
unneccessary           unnecessary
unneccessay            unnecessary
unsellectected         unselected
unsuccesful            unsuccessful
unuseable              unusable
unusuable              unusable
unvailable             unavailable
uploades               uploads
upppercase             uppercase
usally                 usually
usefull                useful
usere                  user
usuable                usable
usuallly               usually
usualy                 usually
utilisation            utilization
vaild                  valid
valied                 valid
valueable              valuable
varb                   verb
vays                   ways
verfication            verification
verically              vertically
versins                versions
verticaly              vertically
verticies              vertices
veryify                verify
vicitim                victim
visiblity              visibility
visualisations         visualizations
visualisation          visualization
visualisation          visualization
visualise              visualize
visul                  visual
volonteer              volunteer
volumen                volume
voribis                vorbis
vrtual                 virtual
waranty                warranty
watseful               wasteful
weigth                 weight
wether                 whether
wheter                 whether
whicn                  which
whishes                wishes
whitch                 which
whith                  with

#incorrect spelling    correction

wiazrd                 wizard
wich                   which
wich                   which
wierd                  weird
wieving                viewing
wiev                   view
wih                    with
willl                  will
wnat                   want
workimg                working
workstatio             workstation
woud                   would
wouldd                 would
writting               writing
writting               writing
yeld                   yield
yesturday              yesterday
yorself                yourself
you'ld                 you would
yourcontrycode         yourcountrycode

