######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 29 17:36:36 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += passbyvalue.cpp

# install
target.path = $$[INSTALL_ROOT]/libexec/krazy-plugins
sources.path = $$[INSTALL_ROOT]/libexec/krazy-plugins/passbyvalue
INSTALLS += target sources
