#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2007 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# FDO desktop file validator.

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --explain:       print an explanation with solving instructions
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use warnings;
use strict;
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::Utils;

my ($Prog)    = "validate";
my ($Version) = "1.43";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f) = $ARGV[0];

my ($valp) = "desktop-file-validate";

# open file and slurp it in
open my $fh, '<:encoding(UTF-8)', $f or die;
my (@data_lines) = <$fh>;
close($fh);

my ($isa) = 0;
foreach my ($line) (@data_lines) {
  Exit 0
    if (
    $line =~ m+^\s*Type=Service+               ||    # ignore Service files
    $line =~ m+^\s*Type=AkonadiAgent+          ||    # ignore AkonadiAgent files
    $line =~ m+^\s*Type=AkonadiResource+       ||    # ignore AkonadiResource files
    $line =~ m+#.*[Kk]razy:excludeall=.*$Prog+ || $line =~ m+#.*[Kk]razy:skip+
    );

  $isa = 1 if ($line =~ m+^\[Desktop Entry\]+);
}
Exit 0 if (!$isa);    #exit if not a true desktop file

#now process the file
my ($cnt) = &processFile($f);
if (!$cnt) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  Exit $cnt;
}

sub Help
{
  print "Validates desktop files using 'desktop-file-validate'\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print
"Please make sure your .desktop files conform to the freedesktop.org standard. See the spec at <https://standards.freedesktop.org/desktop-entry-spec/latest>\n";
  Exit 0 if &explainArg();
}

sub processFile()
{
  my ($in) = @_;
  my ($result);
  my ($cnt) = 0;
  open(VAL, "$valp --warn-kde $in | ") || print STDERR "Cannot run: $valp\n";    ## no critic
  while (my ($line) = <VAL>) {
    chomp($line);
    $result = &analyze($line);
    if ($result && $line) {

      #warnings we allow
      next if ($line =~ m/value \"Service\" for key \"Type\"/);
      next if ($line =~ m/value \"ServiceType\" for key \"Type\"/);
      next if ($line =~ m/value \"Theme\" for key \"Type\"/);
      next if ($line =~ m/file contains group \"PropertyDef:/);
      next if ($line =~ m/key \"InitialPreference\" in group \"Desktop Entry\"/);
      next if ($line =~ m/looks redundant with value/);
      next if ($line =~ m/looks the same as that of key/);

      $cnt++;
      $line =~ s+^$f:\s*++;
      $line =~ s+^warning:\s*++;
      $line =~ s+^error:\s*++;
      $line =~ s+\(will be fatal in the future\): ++;
      print "$line\n" if (!&quietArg());
    }
  }
  close(VAL);
  return $cnt;
}

sub analyze()
{
  my ($line) = @_;

  if ($line =~ m+: error:+) {
    return "ERROR";
  }
  if ($line =~ m+: warning:+) {
    return "WARNING";
  }
  return "";
}
