# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: (^testdata/extras|testdata/plugins)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-json
  - id: check-symlinks
  - id: destroyed-symlinks
  - id: check-executables-have-shebangs
- repo: https://github.com/perltidy/perltidy
  rev: "20260705.01"
  hooks:
  - id: perltidy
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.3
  hooks:
  - id: codespell
    exclude: (plugins/general/spelling|plugins/general/iconnames|share/kpartgui.dtd)
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.13.1-1
  hooks:
  - id: shfmt
    args: ["--indent", "2"]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks:
  - id: shellcheck
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.23.2
  hooks:
  - id: markdownlint-cli2
    files: \.(md|mdown|markdown)$
- repo: https://github.com/fsfe/reuse-tool
  rev: v6.2.0
  hooks:
  - id: reuse
