#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2017 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# JSON file validator using Perl::JSON

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --explain:       print an explanation with solving instructions
#   --installed      file is to be installed
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use strict;
use JSON    qw(decode_json);
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::Utils;

my ($Prog)    = "validate";
my ($Version) = "0.1";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f) = $ARGV[0];

#now process the file
my ($lstr) = "";
my ($cnt)  = &processFile($f);
if (!$cnt) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  print "$lstr\n" if (!&quietArg());
  Exit $cnt;
}

sub Help
{
  print "Validate JSON files using 'Perl::JSON'\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print
"Please make sure your .json files are properly formatted and decodeable, see the RFC at <https://www.ietf.org/rfc/rfc4627.txt>\n";
  Exit 0 if &explainArg();
}

sub processFile()
{
  my ($filename)  = @_;
  my ($json_text) = do {
    open(my $json_fh, "<:encoding(iso-8859-1)", $filename)
      or die("Can't open \"$filename\": $!\n");
    local $/;
    <$json_fh>;
  };

  my ($data) = eval {decode_json($json_text)};

  if ($@) {
    $lstr = "decode failure";
    print "=> $@\n" if (&verboseArg());
    return 1;
  }
  return 0;
}
