#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2007 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# Tests source for incorrect use of cpp macros

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --check-sets:    list of checksets
#   --explain:       print an explanation with solving instructions
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use warnings;
use strict;
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::PreProcess;
use Krazy::Utils;

my ($Prog)    = "cpp";
my ($Version) = "1.90";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f) = $ARGV[0];

# C/C++ only, installed headers only
unless (&fileType($f) eq "c++" && !isPrivateSource($f)) {
  print "okay\n" if (!&quietArg());
  Exit 0;
}

# open file and slurp it in
open my $fh, '<:encoding(UTF-8)', $f or die;
my (@data_lines) = <$fh>;
close($fh);

# Remove C-style comments and #if 0 blocks from the file input
my (@lines) = RemoveIfZeroBlockC(RemoveCommentsC(@data_lines));

# Remove Krazy conditional blocks
@lines = RemoveCondBlockC($Prog, @lines);

# init
my ($cnt)     = 0;
my ($hcnt)    = 0;
my ($wcnt)    = 0;
my ($linecnt) = 0;
my ($lstr)    = "";
my ($hstr)    = "";
my ($wstr)    = "";

my (@OS)   = ();
my (@COMP) = ();

# Check Condition
foreach my ($line) (@lines) {
  if ( $line =~ m+//.*[Kk]razy:excludeall=.*$Prog+
    || $line =~ m+//.*[Kk]razy:skip+)
  {
    $cnt = 0;
    last;
  }

  $linecnt++;
  next if ($line =~ m+//.*[Kk]razy:exclude=.*$Prog+);
  $line =~ s+//.*++;    #skip C++ comments

  if ( $line =~ m/^[[:space:]]*#[[:space:]]*if[[:space:]][_[:alnum:]]/
    || $line =~ m/^[[:space:]]*#[[:space:]]*if[[:space:]]\!def/
    || $line =~ m/^[[:space:]]*#[[:space:]]*ifdef[[:space:]][_[:alnum:]]/
    || $line =~ m/^[[:space:]]*#[[:space:]]*ifndef[[:space:]][_[:alnum:]]/
    || $line =~ m/^[[:space:]]*#[[:space:]]*elif[[:space:]][_[:alnum:]]/)
  {
    next if ($line =~ m/if[[:space:]][01]$/);
    next if ($line =~ m/ifndef[[:space:]].*_H/);
    next if ($line =~ m/ifndef[[:space:]].*_h/);
    next if ($line =~ m/DEBUG/ || $line =~ m/VERBOSE/);

    #    next if ($line =~ m/QT/);
    next if ($line =~ m/KDE/);
    next if ($line =~ m/EXPORT/);
    if ( &osMacros($line, $lines[$linecnt]) >= 0
      || &compilerMacros($line, $lines[$linecnt]) >= 0)
    {
      my ($res) = join(',', @OS, @COMP);
      $cnt++;
      if ($cnt == 1) {
        $lstr = "O/S or Compiler specific macro line\#" . $linecnt . "[$res]";
      } else {
        $lstr = $lstr . "," . $linecnt . "[$res]";
      }
      print "=> $line\n" if (&verboseArg());
    }
    next;
  }

  if ( &usingKDECheckSet()
    && $line =~ m/^[[:space:]]*#[[:space:]]*warning/)
  {
    if (!&searchBack('\s*#\s*ifdef\s__GNUC__', $linecnt - 1, 3)) {
      $wcnt++;
      if ($wcnt == 1) {
        $wstr = "Guard #warning with '#ifdef __GNUC__' line\#" . $linecnt;
      } else {
        $wstr = $wstr . "," . $linecnt;
      }
      print "=> $line\n" if (&verboseArg());
    }
    next;
  }
}

my ($total_count) = $cnt + $hcnt + $wcnt;
if (!$total_count) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  if (!&quietArg()) {
    print "$lstr ($cnt)\n"  if ($cnt);
    print "$hstr ($hcnt)\n" if ($hcnt);
    print "$wstr ($wcnt)\n" if ($wcnt);
  }
  Exit $total_count;
}

# search the previous $n lines for a pattern $p
sub searchBack
{
  my ($p, $l, $n) = @_;
  my ($i);
  $n = $#lines if ($#lines < $n);
  for ($i = 1 ; $i <= $n ; $i++) {
    if ($lines[$l - $i] =~ $p) {
      return 1;
    }
  }
  return 0;
}

sub Help
{
  print "Check for cpp macros and usage\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print
"C/C++ source files and non-installed headers should NOT use cpp conditionals that check for a certain O/S or compiler; instead use HAVE_foo macros. We want to check for features discovered during configure-time rather than for a specific O/S.\n";
  Exit 0 if &explainArg();
}

#Date:   Tue May 26 12:06:53 2009 +0000
#Author: winterz <winterz@283d02a7-25f6-0310-bc7c-ecb5cbfe19da>
#no longer check for Q_OS_* or Q_CC_* because they are almost always correct
#and having krazy exclude directives all over the place is ugly.

sub osMacros()
{
  my ($l, $lp1) = @_;

  @OS = ();
  my (@haves) = split(',', &haves($l));
  if ($#haves >= 0) {
    foreach my ($have) (@haves) {
      if (
           $have =~ m/USE_SOLARIS/
        || $have =~ m/USE_NETBSD/
        || $have =~ m/USE_FREEBSD/
        || $have =~ m/_WIN32/
        || $have =~ m/_WIN64/
        || $have =~ m/Q_OS_WINDOWS/
        ||    #common mistake, should be Q_OS_WIN (requested by Sergio, 9/2/15)
           $have =~ m/__APPLE__/
        || $have =~ m/__svr4__/
        || $have =~ m/__SVR4/
        || $have =~ m/__linux__/
        || $have =~ m/__bsdi__/
        || $have =~ m/__FreeBSD__/
        || $have =~ m/__NetBSD__/
        || $have =~ m/__OpenBSD__/
        || $have =~ m/__DragonFly__/
        || $have =~ m/__osf__/
        || $have =~ m/__hpux/
        || $have =~ m/sun/
        || $have =~ m/sgi/
        || $have =~ m/_AIX/
        || $have =~ m/__CYGWIN__/
        )
      {
        push(@OS, $have);
      }
    }
  }
  return $#OS;
}

sub compilerMacros()
{
  my ($l, $lp1) = @_;

  @COMP = ();
  return -1 if ($l =~ m/__GNUC_MINOR__/);

  my (@haves) = split(',', &haves($l));
  if ($#haves >= 0) {
    foreach my ($have) (@haves) {
      $have =~ s/[<>=].*$//;
      push(@COMP, $have)
        if ($have =~ m/__BORLANDC__/
        || $have =~ m/__INTEL_COMPILER/
        || $have =~ m/_MSC_VER/
        || $have =~ m/__MINGW32__/);
    }
  }

  # stop complaining about __GNUC__ (see Issue#8)
  #if ($l =~ m/__GNUC__/ && $lp1 !~ /warning/){
  #  push(@COMP,"__GNUC__");
  #}
  return $#COMP;
}

sub haves()
{
  my ($l)   = @_;
  my (@a)   = split(' ', $l);
  my ($res) = "";
  foreach my ($guy) (@a) {
    next unless ($guy =~ m/_/);
    next if ($guy =~ m/HAVE_/);
    $guy =~ s/.*defined\(//;
    $guy =~ s/.*\(//;
    $guy =~ s/\).*//;
    $res .= $guy . ",";
  }

  #special cases without underscores
  foreach my ($guy) (@a) {
    $guy =~ s/.*defined\(//;
    $guy =~ s/.*\(//;
    $guy =~ s/\).*//;
    if ( $guy eq "WIN32"
      || $guy eq "WIN64"
      || $guy eq "sun"
      || $guy eq "sgi")
    {
      $res .= $guy . ",";
    }
  }
  $res =~ s/,$//;
  return $res;
}
