#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2006 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# Tests KDE source for QString == "" compares

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --explain:       print an explanation with solving instructions
#   --installed      file is to be installed
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use strict;
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::PreProcess;
use Krazy::Utils;

my ($Prog)    = "emptystrcompare";
my ($Version) = "1.3";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f) = $ARGV[0];

# skip C source files
if ($f =~ m/\.c$/) {
  print "okay\n" if (!&quietArg());
  Exit 0;
}

#open file and slurp it in
open(F, "$f") || die "Couldn't open $f";
my (@data_lines) = <F>;
close(F);

# Remove C-style comments and #if 0 blocks from the file input
my (@lines) = RemoveIfZeroBlockC(RemoveCommentsC(@data_lines));

my ($cnt)     = 0;
my ($linecnt) = 0;
my ($line);
my ($lstr) = "";
foreach $line (@lines) {
  if ( $line =~ m+//.*[Kk]razy:excludeall=.*$Prog+
    || $line =~ m+//.*[Kk]razy:skip+)
  {
    $cnt = 0;
    last;
  }
  $linecnt++;
  next if ($line =~ m+//.*[Kk]razy:exclude=.*$Prog+);

  $line =~ s+//.*++;    #skip C++ comments
  if ( $line =~ m/==[[:space:]]*\"\"/
    || $line =~ m/\"\"[[:space:]]*==/
    || $line =~ m/!=[[:space:]]*\"\"/
    || $line =~ m/\"\"[[:space:]]*!=/)
  {
    next if ($line =~ m/;/);
    $cnt++;
    if ($cnt == 1) {
      $lstr = "line\#" . $linecnt;
    } else {
      $lstr = $lstr . "," . $linecnt;
    }
    print "=> $line" if (&verboseArg());
  }
}

if (!$cnt) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  print "$lstr ($cnt)\n" if (!&quietArg());
  Exit $cnt;
}

sub Help
{
  print "Check for QString compares to \"\"\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print
"Do not compare a QString to \"\".  Instead use the .isEmpty() method.  For example, if(str == \"\") becomes if(str.isEmpty())\n";
  Exit 0 if &explainArg();
}
