#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2008 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# Tests KDE/Qt source for QByteArray issues.

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --explain:       print an explanation with solving instructions
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use warnings;
use strict;
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::PreProcess;
use Krazy::Utils;

my ($Prog)    = "qbytearray";
my ($Version) = "1.1";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f) = $ARGV[0];

# C++, non-headers only
unless ((&usingKDECheckSet() || &usingQtCheckSet()) && !isCSource($f) && !isCInclude($f)) {
  print "okay\n" if (!&quietArg());
  Exit 0;
}

# open file and slurp it in
open my $fh, '<:encoding(UTF-8)', $f or die;
my (@data_lines) = <$fh>;
close($fh);

# Remove C-style comments and #if 0 blocks from the file input
my (@lines) = RemoveIfZeroBlockC(RemoveCommentsC(@data_lines));

my ($dcnt)    = 0;    #QString data()/constData() issues
my ($linecnt) = 0;
my ($dlstr)   = "";
foreach my ($line) (@lines) {
  if ( $line =~ m+//.*[Kk]razy:excludeall=.*$Prog+
    || $line =~ m+//.*[Kk]razy:skip+)
  {
    $dcnt = 0;
    last;
  }

  $linecnt++;
  next if ($line =~ m+//.*[Kk]razy:exclude=.*$Prog+);
  $line =~ s+//.*++;    #skip C++ comments

  #data(), constData() checks
  if ($line =~ m:[\w\s]+=\s*\w+\.(toLatin1|toAscii|toUtf8|toLocal8Bit)\(\)\.(data|constData)\(\):) {
    $dcnt++;
    if ($dcnt == 1) {
      $dlstr = "data assignment issues line\#" . $linecnt;
    } else {
      $dlstr = $dlstr . "," . $linecnt;
    }
    print "=> $line\n" if (&verboseArg());
    next;
  }
}

my ($total_count) = $dcnt;
if (!$total_count) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  if (!&quietArg()) {
    print "$dlstr ($dcnt)\n" if ($dcnt);
  }
  Exit $total_count;
}

sub Help
{
  print "Check for dangerous or inefficient QByteArray usage\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print
"Do not assign the result of QString::QByteArray.data() or QString::QByteArray::constData(); instead use temporary storage.  For example, data=str.toAscii().data() is safer as QByteArray b=str.toAscii(); data=b.data()\n";
  Exit 0 if &explainArg();
}
