#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2007 Thorsten Roeder <thorsten.roeder@weihenstephan.org> #
# SPDX-FileCopyrightText: 2012 Allen Winter <winter@kde.org>                  #
#                                                                             #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# Tests KDE source for classes that should use the Q_OBJECT macro if derived
# from QObject

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --explain:       print an explanation with solving instructions
#   --installed      file is to be installed
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use warnings;
use strict;
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::PreProcess;
use Krazy::Utils;

my ($Prog)    = "qobject";
my ($Version) = "1.22";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f) = $ARGV[0];

# C++, headers only
if (isCSource($f) || !isCInclude($f)) {
  print "okay\n" if (!&quietArg());
  Exit 0;
}

# open file and slurp it in
open my $fh, '<:encoding(UTF-8)', $f or die;
my (@data_lines) = <$fh>;
close($fh);

# Remove C-style comments and #if 0 blocks from the file input
my (@lines) = RemoveIfZeroBlockC(RemoveCommentsC(@data_lines));

my ($cnt)      = 0;
my ($classcnt) = 0;
my (%classline);
my ($linecnt) = 0;
my ($line);
my ($lstr) = "";

# TODO: line numbering maybe incorrect if a macro is missing inside nested classes (rare case)
my ($lastl) = "";    #lastline
while ($linecnt < $#lines) {
  $lastl = $line;
  $line  = $lines[$linecnt++];
  if ( $line =~ m+//.*[Kk]razy:excludeall=.*$Prog+
    || $line =~ m+//.*[Kk]razy:skip+)
  {
    $cnt = 0;
    last;
  }

  if ($line =~
m/[[:space:]]*class[[:space:]]+[[:alnum:]]+[[:space:]]*:[[:space:]]*[[:alnum:]]+[[:space:]]+QObject/
    )
  {
    next if ($lastl =~ m/template/ || $lastl =~ m/#define[[:space:]]/ || $lastl =~ m/#if/);
    next if ($line =~ m/QObjectPrivate/ || $line =~ m+//.*[Kk]razy:exclude=.*$Prog+);

    $classcnt++;
    $classline{$classcnt} = $linecnt;
  } elsif ($line =~ m/Q_OBJECT/) {
    delete $classline{$classcnt} if exists $classline{$classcnt};
    $classcnt--;
  }
}

my (@classlinekeys) = sort keys(%classline);
foreach (@classlinekeys) {
  $cnt++;
  if ($cnt == 1) {
    $lstr = "line\#" . $classline{$_};
  } else {
    $lstr = $lstr . "," . $classline{$_};
  }

  #    print "=> $lines[$classline{$_}]" if (&verboseArg());
}

if (!$cnt) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  print "$lstr ($cnt)\n" if (!&quietArg());
  Exit $cnt;
}

sub Help
{
  print "Check for classes that should use the \'Q_OBJECT\' macro\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print
"QObject derived classes should use the Q_OBJECT macro.\nclass A : public QObject {...} becomes class A : public QObject { Q_OBJECT ... }\n";
  Exit 0 if &explainArg();
}
