#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2008 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# Tests Qt/KDE source for system calls

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --check-sets:    list of checksets
#   --explain:       print an explanation with solving instructions
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use warnings;
use strict;
use Cwd 'abs_path';
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::PreProcess;
use Krazy::Utils;

my ($Prog)    = "syscalls";
my ($Version) = "1.61";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f)    = $ARGV[0];
my ($absf) = abs_path($f);

# C++, non-headers only
if (isCSource($f) || isCInclude($f)) {
  print "okay\n" if (!&quietArg());
  Exit 0;
}

# open file and slurp it in
open my $fh, '<:encoding(UTF-8)', $f or die;
my (@data_lines) = <$fh>;
close($fh);

# Remove C-style comments and #if 0 blocks from the file input
my (@lines) = RemoveIfZeroBlockC(RemoveCommentsC(@data_lines));

# Remove Krazy conditional blocks
@lines = RemoveCondBlockC($Prog, @lines);

my ($cnt)     = 0;
my ($linecnt) = 0;
my ($lstr)    = "";

my ($line);
while ($linecnt < $#lines) {
  $line = $lines[$linecnt++];
  if ( $line =~ m+//.*[Kk]razy:excludeall=.*$Prog+
    || $line =~ m+//.*[Kk]razy:skip+)
  {
    $cnt = 0;
    last;
  }
  next if ($line =~ m+//.*[Kk]razy:exclude=.*$Prog+);
  $line =~ s+//.*++;    #skip C++ comments

  if (&usingQtCheckSet() || &usingKDECheckSet()) {
    &doIt($line, "chdir",     "QDir::cd");
    &doIt($line, "mkdir",     "QDir::mkpath");
    &doIt($line, "rmdir",     "QDir::rmpath");
    &doIt($line, "rename",    "QFile::rename");
    &doIt($line, "stat",      "QFile");
    &doIt($line, "stat64",    "QFile");
    &doIt($line, "lstat",     "QFile");
    &doIt($line, "lstat64",   "QFile");
    &doIt($line, "fstat",     "QFile");
    &doIt($line, "fstat64",   "QFile");
    &doIt($line, "open",      "QFile::open");
    &doIt($line, "open64",    "QFile::open");
    &doIt($line, "lseek",     "QFile::seek");
    &doIt($line, "lseek64",   "QFile::seek");
    &doIt($line, "fseek",     "QFile::seek");
    &doIt($line, "fseek64",   "QFile::seek");
    &doIt($line, "ftell",     "QFile::pos");
    &doIt($line, "ftell64",   "QFile::pos");
    &doIt($line, "fgetpos",   "QFile::pos");
    &doIt($line, "fgetpos64", "QFile::pos");
    &doIt($line, "fsetpos",   "QFile::pos");
    &doIt($line, "fsetpos64", "QFile::pos");
    &doIt($line, "readdir",   "QDir");
    &doIt($line, "readdir64", "QDir");

    &doIt($line, "truncate",   "QFile::resize");
    &doIt($line, "truncate64", "QFile::resize");
    &doIt($line, "ftruncate",  "QFile::resize");
    &doIt($line, "truncate64", "QFile::resize");

    &doIt($line, "fopen",   "QFile");
    &doIt($line, "fopen64", "QFile");

    &doIt($line, "access", "QFile::permissions");
    &doIt($line, "getcwd", "QDir::path");

    &doIt($line, "rand",  "QRandomGenerator");
    &doIt($line, "srand", "QRandomGenerator");

    &doIt($line, "getenv",   "qgetenv");
    &doIt($line, "putenv",   "qputenv");
    &doIt($line, "::setenv", "qputenv");

    &doIt2($line, 'struct\s*stat[\s\*]',     "struct stat",     "QFile");
    &doIt2($line, 'struct\s*stat64[\s\*]',   "struct stat64",   "QFile");
    &doIt2($line, 'struct\s*dirent[\s\*]',   "struct dirent",   "QDir");
    &doIt2($line, 'struct\s*dirent64[\s\*]', "struct dirent64", "QDir");
  }
}

if (!$cnt) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  $lstr =~ s/,$//;
  print "$lstr ($cnt)\n" if (!&quietArg());
  Exit $cnt;
}

sub doIt()
{
  my ($line, $syscall, $kname) = @_;
  if (&sysCall($line, $syscall)) {
    $cnt++;
    if ($cnt == 1) {
      $lstr = "line\#" . $linecnt;
    } else {
      $lstr = $lstr . "," . $linecnt;
    }
    $lstr .= " $syscall" . "[$kname]";
    print "=> $line\n" if (&verboseArg());
  }
}

sub doIt2()
{
  my ($line, $regex, $systype, $kname) = @_;
  if (&sysType($line, $regex)) {
    $cnt++;
    if ($cnt == 1) {
      $lstr = "line\#" . $linecnt;
    } else {
      $lstr = $lstr . "," . $linecnt;
    }
    $lstr .= " $systype" . "[$kname]";
    print "=> $line\n" if (&verboseArg());
  }
}

sub sysCall()
{
  my ($l, $syscall) = @_;
  if ( $l =~ m/[\(,;=:]\s*$syscall[[:space:]]*\(/
    || $l =~ m/^\s*$syscall[[:space:]]*\(/)
  {
    if ( $l !~ m/[[:alnum:]]::$syscall/
      && $l !~ m/SIGNAL/
      && $l !~ m/emit/
      && $l !~ m/open.*\"\s*\)/
      && $l !~ m/close\s*\(\s*\"/
      && $l !~ m/open\s*\(\s*\)/
      && $l !~ m/open\s*\(.*[Ff][Aa][Ll][Ss][Ee].*\)/
      && $l !~ m/open\s*\(.*[Tt][Rr][Uu][Ee].*\)/
      && $l !~ m/close\s*\(.*[Ff][Aa][Ll][Ss][Ee].*\)/
      && $l !~ m/close\s*\(.*[Tt][Rr][Uu][Ee].*\)/)
    {
      return 1;
    }
  } else {
    return 0;
  }
}

sub sysType()
{
  my ($l, $systype) = @_;
  if ($l =~ m/^\s*$systype/) {
    return 1;
  } else {
    return 0;
  }
}

sub Help
{
  print "Check for system calls to replace by KDE or Qt equivalents\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print "Some system calls are not portable, please use the suggested portable wrapper instead. ";
  if (&usingQtCheckSet() || &usingKDECheckSet()) {
    print "See qplatformdefs.h\n";
  }
  Exit 0 if &explainArg();
}
