#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2006 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# Tests KDE source for unwanted doxygen tags in major releases.

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --explain:       print an explanation with solving instructions
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use warnings;
use strict;
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::Utils;
use Cwd 'abs_path';

my ($Prog)    = "doxytags";
my ($Version) = "1.3";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f)  = $ARGV[0];
my ($ff) = abs_path($f);
if ($ff =~ m+/branches/+ || $ff =~ m+/kde-3\.5/+) {
  print "okay\n" if (!&quietArg());
  Exit 0;
}

# open file and slurp it in
open my $fh, '<:encoding(UTF-8)', $f or die;
my (@data_lines) = <$fh>;
close($fh);

my ($cnt)     = 0;
my ($linecnt) = 0;
my ($lstr)    = "";
foreach my ($line) (@data_lines) {
  if ( $line =~ m+//.*[Kk]razy:excludeall=.*$Prog+
    || $line =~ m+//.*[Kk]razy:skip+)
  {
    $cnt = 0;
    last;
  }
  $linecnt++;
  if ($line =~ m/\@since 4\.0[^\.]/) {    # @since 4.0.1 or 4.1 is ok, @since 4.0 is not
    $cnt++;
    if ($cnt == 1) {
      $lstr = "line\#" . $linecnt;
    } else {
      $lstr = $lstr . "," . $linecnt;
    }
    print "=> $line" if (&verboseArg());
  }
}

if (!$cnt) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  print "$lstr ($cnt)\n" if (!&quietArg());
  Exit $cnt;
}

sub Help
{
  print "Check for unwanted doxygen tags in major versions\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print
"The \"\@since\" doxygen tag should not be used in the API documentation for major versions (i.e. 4.0).  Please remove those tags. \"\@since 4.0.1\" or \"\@since 4.1\" is OK of course.\n";
  Exit 0 if &explainArg();
}
