#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2007 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# Tests KDE source for <condition>

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --explain:       print an explanation with solving instructions
#   --installed      file is to be installed
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use warnings;
use strict;
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::Utils;

my ($Prog)    = "rcappend";
my ($Version) = "1.1";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

# Check Condition
my ($f) = $ARGV[0];

unless (&usingKDECheckSet()) {
  print "okay\n" if (!&quietArg());
  Exit 0;
}

my ($cnt)     = 0;
my ($linecnt) = 0;
my ($lstr)    = "";

# open file and slurp it in
open my $fh, '<:encoding(UTF-8)', $f or die;
my (@data_lines) = <$fh>;
close($fh);

foreach my ($line) (@data_lines) {
  $linecnt++;
  if ( $line =~ m+#.*[Kk]razy:excludeall=.*$Prog+
    || $line =~ m+#.*[Kk]razy:skip+)
  {
    $cnt = 0;
    last;
  }

  next if ($line =~ m+#.*[Kk]razy:exclude=.*$Prog+);
  $line =~ s+#.*++;    #skip comments

  if ($line =~ m/[[:space:]]*>[[:space:]]*rc\.cpp/ && $line !~ m/>>[[:space:]]*rc\.cpp/) {
    $cnt++;
    if ($cnt == 1) {
      $lstr = "line\#" . $linecnt;
    } else {
      $lstr = $lstr . "," . $linecnt;
    }
    print "=> $line" if (&verboseArg());
  }
}

if (!$cnt) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  print "$lstr ($cnt)\n" if (!&quietArg());
  Exit $cnt;
}

sub Help
{
  print "Check for appending to rc.cpp\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print "Always append extracted messages to the rc.cpp with '>>' shell redirection.\n";
  Exit 0 if &explainArg();
}
