#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2008 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# Tests KDE source for kDebug or qCDebug issues

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --priority:      report issues of the specified priority only
#   --strict:        report issues with the specified strictness level only
#   --explain:       print an explanation with solving instructions
#   --installed      file is to be installed
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use warnings;
use strict;
use Cwd 'abs_path';
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::PreProcess;
use Krazy::Utils;

my ($Prog)    = "kdebug";
my ($Version) = "1.22";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f) = $ARGV[0];

# C++ files only
unless (&usingKDECheckSet() && !isCSource($f)) {
  print "okay\n" if (!&quietArg());
  Exit 0;
}

# open file and slurp it in
open my $fh, '<:encoding(UTF-8)', $f or die;
my (@data_lines) = <$fh>;
close($fh);

# Remove C-style comments and #if 0 blocks from the file input
my (@lines) = RemoveIfZeroBlockC(RemoveCommentsC(@data_lines));

my ($acnt)    = 0;
my ($ecnt)    = 0;
my ($mcnt)    = 0;
my ($linecnt) = 0;
my ($alstr)   = "";
my ($elstr)   = "";
my ($mlstr)   = "";

my ($line);
while ($linecnt < $#lines) {
  $line = $lines[$linecnt++];
  if ( $line =~ m+//.*[Kk]razy:excludeall=.*$Prog+
    || $line =~ m+//.*[Kk]razy:skip+)
  {
    $acnt = $ecnt = $mcnt = 0;
    last;
  }
  next if ($line =~ m/^\s*#\s*define\s*.*/);
  next if ($line =~ m+//.*[Kk]razy:exclude=.*$Prog+);
  $line =~ s+//.*++;    #skip C++ comments

  #debug areas
  if ($line =~ m+(qC|k)(Debug|Warning|Error)\s*\(\s*[[:digit:]]\s*+) {
    $acnt++;
    if ($acnt == 1) {
      $alstr = "line\#" . $linecnt;
    } else {
      $alstr = $alstr . "," . $linecnt;
    }
    print "=> $line\n" if (&verboseArg());
  }

  #endl;
  if ($line =~ m+(qC|k)(Debug|Warning|Error).*endl\s*;\s*$+) {
    $ecnt++;
    if ($ecnt == 1) {
      $elstr = "line\#" . $linecnt;
    } else {
      $elstr = $elstr . "," . $linecnt;
    }
    print "=> $line\n" if (&verboseArg());
  }

  #method
  my ($pline) = $line;
  $pline =~ s/\".*\"/\"\"/g;    #ignore anything in double-quotes
  $pline =~ s/QDate.*:://g;
  $pline =~ s/QDir.*:://g;
  $pline =~ s/QFile.*:://g;
  $pline =~ s/QString.*:://g;
  $pline =~ s/KGlobal.*:://g;
  $pline =~ s/KLocale.*:://g;
  $pline =~ s/KSystem.*:://g;

  if ( $pline =~ m+(qC|k)(Debug|Warning|Error).*::.*\(+
    || $pline =~ m+(qC|k)(Debug|Warning|Error).*k_funcinfo+)
  {
    if ( $pline !~ m/<[\w:]+>\(/
      && $pline !~ m/\.[\w]+\(/
      && $pline !~ m/->[\w]+\(/)
    {
      $mcnt++;
      if ($mcnt == 1) {
        $mlstr = "line\#" . $linecnt;
      } else {
        $mlstr = $mlstr . "," . $linecnt;
      }
      print "=> $line\n" if (&verboseArg());
    }
  }
}

my ($total_count) = $acnt + $ecnt + $mcnt;
if (!$total_count) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  if (!&quietArg()) {
    print "using debug areas: $alstr ($acnt)"    if ($acnt);
    print ", "                                   if ($acnt && $mcnt);
    print "printing method name: $mlstr ($mcnt)" if ($mcnt);
    print ", "                                   if (($mcnt || $acnt) && $ecnt);
    print "using endl: $elstr ($ecnt)"           if ($ecnt);
    print "\n";
  }
  Exit $total_count;
}

sub Help
{
  print "Check for kDebug and qCDebug issues\n";
  Exit 0 if &helpArg();
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if &versionArg();
}

sub Explain
{
  print
"No need to print the method name or a trailing endl with kDebug/qCDebug and friends -- all that is done for you as if by magic.\n";
  Exit 0 if &explainArg();
}
