#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
  if 0;    # not running under some shell
###############################################################################
# Sanity check plugin for the Krazy project.                                  #
# SPDX-FileCopyrightText: 2007 Allen Winter <winter@kde.org>                  #
# SPDX-License-Identifier: GPL-2.0-or-later                                   #
###############################################################################

# Tests KDE source for prohibited KDE Classes in the public API

# Program options:
#   --help:          print one-line help message and exit
#   --version:       print one-line version information and exit
#   --explain:       print an explanation with solving instructions
#   --installed      file is to be installed
#   --quiet:         suppress all output messages
#   --verbose:       print the offending content

# Exits with status=0 if test condition is not present in the source;
# else exits with the number of failures encountered.

use warnings;
use strict;
use FindBin qw($Bin);
use lib "$Bin/../../../../lib";
use Krazy::PreProcess;
use Krazy::Utils;

my ($Prog)    = "kclasses";
my ($Version) = "1.0";

&parseArgs();

&Help()    if &helpArg();
&Version() if &versionArg();
&Explain() if &explainArg();
if ($#ARGV != 0) {&Help(); Exit 0;}

my ($f) = $ARGV[0];

# C++ files only
unless (&usingKDECheckSet() && &fileType($f) eq "c++" && !isCSource($f) && !isPublicSource($f)) {
  print "okay\n" if (!&quietArg());
  Exit 0;
}

# open file and slurp it in
open my $fh, '<:encoding(UTF-8)', $f or die;
my (@data_lines) = <$fh>;
close($fh);

#get all the c-style comments from the file
my ($data)     = "@data_lines";
my (@comments) = ($data =~ /\/\*.*?\*\//gs);

#for each comment, remove everything but the linebreaks, so
#our line numbering report does not get screwed up.
foreach my $comment (@comments) {
  my ($fixed_comment) = $comment;
  $fixed_comment =~ s/[^\n]//gs;
  $fixed_comment =~ s/\n/\n/gs;
  $data          =~ s/\Q$comment/$fixed_comment/s;
}

#put it back into an array so we can iterate over it
my (@lines) = split(/\n/, $data);

my ($cnt)     = 0;
my ($linecnt) = 0;
my ($lstr)    = "";

my ($line);
while ($linecnt < $#lines) {
  $line = $lines[$linecnt++];
  if ( $line =~ m+//.*[Kk]razy:excludeall=.*$Prog+
    || $line =~ m+//.*[Kk]razy:skip+)
  {
    $cnt = 0;
    last;
  }
  &doIt($line, "KAction", "QAction");
}

if (!$cnt) {
  print "okay\n" if (!&quietArg());
  Exit 0;
} else {
  $lstr =~ s/,$//;
  print "$lstr ($cnt)\n" if (!&quietArg());
  Exit $cnt;
}

sub doIt()
{
  my ($line, $kname, $qname) = @_;
  if ($f !~ m/$kname\.h/i && &kClass($line, $kname)) {
    $cnt++;
    $lstr .= $kname . "[$qname],";
    print "=> $line\n" if (&verboseArg());
  }
}

sub kClass()
{
  my ($l, $kname) = @_;
  if ( $l =~ m/^[[:space:]]*class[[:space:]]$kname[[:space:]]*;/
    || $l =~ m/$kname[[:space:]]*\*/)
  {
    # TODO: or include <KAction> or include <kaction.h> or QList <KAction> or QList <KAction*> return 1;
  } else {
    return 0;
  }
}

sub Help
{
  print "Check for KDE classes that should not be used\n";
  Exit 0 if (&helpArg());
}

sub Version
{
  print "$Prog, version $Version\n";
  Exit 0 if (&verboseArg());
}

sub Explain
{
  print "Use Qt classes in the public API instead of the KDE counterparts.\n";
  Exit 0 if (&explainArg());
}
