=pod

=head1 krazyrc

.krazy - krazy control directives

=head1 DESCRIPTION

.krazy files provide directives that control how the Krazy Code Checking
tools perform within a KDE source directory.

Each line in the file can be a control directive, a blank line,
or a comment. Comment lines start with the # character.

If multiple instances of a directive are specified they will be
merged together in a logical way.

=head1 DIRECTIVES

The following directives are understood by the Krazy Code Checking tools:

=over 1

=item EXCLUDE plugin1[,plugin2,...]

Remove the specified plugins from the default set of checkers.

=item CHECK plugin1[,plugin2,...]

Run only the specified list of plugins from the default set of checkers.
You may not combine this with the CHECKSET directive nor with the B<--check-sets> 
command line option.

I<Note>: the CHECK directive takes precedence over the EXCLUDE directive;
i.e, plugins specified by the CHECK directive are always run, even if
they are also specified in an EXCLUDE directive.


=item CHECKSETS set1[,set2,...]

Run the checker programs belonging to the specified set(s) only.
You may not combine this with the CHECK directive nor with the B<--check> 
command line option.


=item EXTRA plugin1[,plugin2,...]

Add the specified list of "extra" plugins to the default set of checkers.

=item TYPES type1[,type2,...]

Check the specifed file type(s) only.

=item EXCLUDETYPES type1[,type2,...]

Do NOT check the specified file type(s).

=item SKIP regexp

Do not process any file that maches the specified perl regular expression.
See the perlreftut(1) man page for a description of how to write
a perl regular expression.
 
=item PRIORITY priority

Set the priority value. Must be one of "low", "normal", "high", "important", "all".

=item STRICT strict

Set the strict value. Must be one of "normal", "super", "all".

=item OUTPUT output

Set the output level. Must be one of "quiet", "brief", "all".

"quiet" means no output is printed, even if --verbose is passed on the command line.

"brief" will only print checker summaries if the check has at least 1 issue.

"all" is the normal mode and prints all checker summaries

=item EXPORT export-type

Set the default export-type value. Must be one of the following:

"text" (default)

"textlist" prints 1 offending file-per-line

"textedit" prints text formatted for IDEs, 1 issue-per-line

"xml" prints XML formatted intended for follow-on processing

=item IGNORESUBS subdir1[,subdir2,...]

Do not run Krazy on the specified list of subdirectories.
These must be KDE "project" subdirectories that reside at
the top level of a KDE module.

IGNORESUBS is an administrator directive used only by the krazy2xml(1) program.

=item EXTRASUBS subdir1[,subdir2,...]

Run Krazy on the specified list of subdirectories.
These must be KDE "project" subdirectories that reside at
the top level of a KDE module.

EXTRASUBS is an administrator directive used only by the krazy2xml(1) program.

=item IGNOREMODS module1[,module2,...]

Do not run Krazy on the specified list of KDE modules.

IGNOREMODS is an administrator directive used only by the krazy2xml(1) program.

=back

=head1 COPYRIGHT

Copyright 2005-2010 by Allen Winter <winter@kde.org>

=head1 SEE ALSO

krazy2(1), krazy2all(1), krazy2xml(1), perlreftut(1)

=head1 AUTHORS

Allen Winter, <winter@kde.org>

=cut

